import numpy as np
print("One dimensional Array")
arr1=np.array([20,34,56,78])
arr2=np.array([0,1,2,3])
print("Array 1:",arr1)
print("Array 2:",arr2)
print("Array1-Array2 =",arr1-arr2)
print("Array2**2 =",arr2**2)

print("Two dimensional Array")
arr3=np.array([[1,2,3],[4,5,6]])
arr4=np.array([[7,8,9],[3,4,5]])
print("Matrix 1:")
print(arr3)
print("Matrix 2:")
print(arr4)
print("matrix Addition:")
print(arr3+arr4)
print("matrix Subtraction:")
print(arr3-arr4)
print("matrix Multiplication:")
print(arr3@arr4)
print("Transpose of Matrix 1")
print(arr3.T)
